### ISSUE TITLE
Parse Error: `AirborneVelocitySubType`

### ISSUE THREAD

**Issue by wcampbell0x2a** [wcampbell0x2a/adsb_deku#22]
```
911c059d9805a452cf109f64924f
thread 'main' panicked at '[E] Parse error: Could not match enum variant id = 0 on enum `AirborneVelocitySubType`', apps/src/1090.rs:87:21
```

**Comment by wcampbell0x2a** [comment]
```
thread 'main' panicked at '[E] Parse error: Could not match enum variant id = 6 on enum `AirborneVelocitySubType`', apps/src/1090.rs:103:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
