### ISSUE TITLE
Parse Error: `OperationStatus`

### ISSUE THREAD

**Issue by wcampbell0x2a** [wcampbell0x2a/adsb_deku#25]
```
92479249fcb22e16fbdc3bac5b56
thread 'main' panicked at '[E] Parse error: Could not match enum variant id = 4 on enum `OperationStatus`', apps/src/1090.rs:100:25
```

**Comment by wcampbell0x2a** [comment]
```
967342a9fd4b0cea25ef5565e34d
thread 'main' panicked at '[E] Parse error: Could not match enum variant id = 5 on enum `OperationStatus`', apps/src/1090.rs:103:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by wcampbell0x2a** [comment]
```
8f2c0e3efde10342c0e5b981c326
thread 'main' panicked at '[E] Parse error: Could not match enum variant id = 5 on enum `OperationStatus`', apps/src/1090.rs:103:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
